spring:
  application:
    name: simple-board
management:
  endpoints:
    web:
      exposure:
        include: heath, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name:simple-board-app}