spring:
  application:
    name: simple-board
  datasource:
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
      connection-timeout: 30000
  cache:
    type: redis
    redis:
      enable-statistics: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      cache: true